id: web-manageengine-applications-manager
info:
  name: manageengine-applications-manager
  author: archer
  verified: false
  description: 检测到manageengine-applications-manager系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"/appmanager.js")
expression: r0()
