id: CVE-2001-1473-udp

info:
  name: Deprecated SSHv1 Protocol Detection
  author: iamthefrogy
  severity: high
  description: SSHv1 is deprecated and has known cryptographic issues.
  reference:
    - https://www.kb.cert.org/vuls/id/684820
    - https://nvd.nist.gov/vuln/detail/CVE-2001-1473
  solutions: Upgrade to SSH 2.4 or later.
  tags: cve,cve2001,network,ssh,openssh
  created: 2022/01/21

set:
  hostname: request.url.host
  host: request.url.domain
rules:
  r0:
    request:
      type: udp
      host: "{{hostname}}"
      data: "test\n"
    expression: response.raw.bcontains(b'SSH-')
  r1:
    request:
      type: udp
      host: "{{host}}:53"
      data: "\n"
    expression: response.raw.bcontains(b'SSH-')
expression: r0() || r1() 