id: web-chinatelecomequipmentwebconfigurationsystem
info:
  name: chinatelecomequipmentwebconfigurationsystem
  author: archer
  verified: false
  description: 检测到chinatelecomequipmentwebconfigurationsystem系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"设备web配置</font")
expression: r0()
