id: web-swagger
info:
  name: swagger
  author: archer
  verified: false
  description: 检测到swagger系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"Swagger UI")
  r1:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"swagger-ui.css")
  r2:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"swagger-ui.js")
expression: r0() || r1() || r2()
