id: web-gzsa-intranet-security
info:
  name: gzsa-intranet-security
  author: archer
  verified: false
  description: 检测到gzsa-intranet-security系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"gzsa. all rights reserved</span>")
expression: r0()
