id: web-rconfig
info:
  name: rconfig
  author: archer
  verified: false
  description: 检测到rconfig系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: response.body.ibcontains(b"rConfigLogo")
expression: r0()
