id: web-sap-web-application-server
info:
  name: sap-web-application-server
  author: archer
  verified: false
  description: 检测到sap-web-application-server系统或组件的特征
  created: 2025/04/24
rules:
  r0:
    request:
      method: GET
      path: /
    expression: 'response.raw_header.ibcontains(b"Server: sap web application server")'
  r1:
    request:
      method: GET
      path: /
    expression: 'response.raw_header.ibcontains(b"Server: sap netweaver application server")'
  r2:
    request:
      method: GET
      path: /
    expression: 'response.raw_header.ibcontains(b"Server: sap j2ee engine")'
expression: r0() || r1() || r2()
